# Generated by Django 3.2.3 on 2021-05-29 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('option', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_fare', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_fare', models.CharField(blank=True, max_length=200, null=True)),
                ('pick_up_location', models.CharField(blank=True, max_length=200, null=True)),
                ('drop_off_location', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_time', models.DurationField(blank=True, max_length=200, null=True)),
                ('actual_time', models.DurationField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_datetime', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('ended_datetime', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('arrived_at_latitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('arrived_at_longitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('arrived_at_datetime', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('accepted_at_latitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('accepted_at_longitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('accepted_at_datetime', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('pick_up_latitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('pick_up_longitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('drop_off_latitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('drop_off_longitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('ride_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='option.option')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
