# Generated by Django 3.2.3 on 2021-06-01 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0005_auto_20210529_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='online_offline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='option.option'),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='option.option'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_fare', models.CharField(blank=True, max_length=200, null=True)),
                ('pick_up_location', models.CharField(blank=True, max_length=200, null=True)),
                ('drop_off_location', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_time', models.DurationField(blank=True, max_length=200, null=True)),
                ('pick_up_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('pick_up_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('drop_off_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('drop_off_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('online_offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='option.option')),
                ('ride_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='option.option')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='option.option')),
            ],
        ),
    ]
