# Generated by Django 3.2.3 on 2021-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_auto_20210601_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='is_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
