# Generated by Django 3.2.3 on 2021-06-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_riderequest_is_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='is_expired',
            new_name='is_alive',
        ),
    ]
