# Generated by Django 3.2.3 on 2021-06-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_rename_is_expired_riderequest_is_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='is_alive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
