# Generated by Django 3.2.3 on 2021-05-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_maker', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
