# Generated by Django 3.2.3 on 2021-05-29 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
        ('vehicle', '0002_vehicle_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='registration_number',
            new_name='vehicle_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='option.option'),
        ),
    ]
