# Generated by Django 3.2.3 on 2021-05-25 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
        ('user', '0002_auto_20210525_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, default=1, max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_id', to='option.option'),
        ),
    ]
