# Generated by Django 3.2.3 on 2021-05-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
        ('user', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_back',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_front',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_id', to='option.option'),
        ),
    ]
