# Generated by Django 3.2.3 on 2021-05-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210529_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineuser',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='onlineuser',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
    ]
