# Generated by Django 3.2.3 on 2021-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210529_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userlivelocation',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
