# Generated by Django 3.2.3 on 2021-06-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210530_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='on_ride',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userlivelocation',
            name='on_ride',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
